{% set name = "demjson3" %}
{% set version = "3.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37c83b0c6eb08d25defc88df0a2a4875d58a7809a9650bd6eee7afd8053cdbac

build:
  number: 0
  noarch: python
  entry_points:
    - jsonlint=jsonlint:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - demjson3
  commands:
    - pip check
    - jsonlint --help
  requires:
    - pip

about:
  home: https://nielstron.github.io/demjson3/
  summary: encoder, decoder, and lint/validator for JSON (JavaScript Object Notation) compliant with RFC 7159.
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  dev_url: https://github.com/nielstron/demjson3

extra:
  recipe-maintainers:
    - marcobonifacio
